"""add required_role_type to positions

Revision ID: 172d7621794f
Revises: 83fc7ae4ec3d
Create Date: 2026-03-03 14:55:07.569484

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '172d7621794f'
down_revision: Union[str, Sequence[str], None] = '83fc7ae4ec3d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('positions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('required_role_type', sa.Enum('SUPERVISOR', 'LOGISTICS', 'LINE_LEAD', 'SR_DOCK', 'GENERAL', name='roletype'), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('positions', schema=None) as batch_op:
        batch_op.drop_column('required_role_type')

    # ### end Alembic commands ###
