"""add_fixed_roles_and_schedulable

Revision ID: 8cf9291d1990
Revises: 9c740d85ded2
Create Date: 2026-03-03 21:08:40.480919

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8cf9291d1990'
down_revision: Union[str, Sequence[str], None] = '9c740d85ded2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('fixed_assignments',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('employee_id', sa.String(), nullable=True),
    sa.Column('position_key', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('employee_id'),
    sa.UniqueConstraint('position_key')
    )
    with op.batch_alter_table('employees', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_schedulable', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('is_fixed_role', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('employees', schema=None) as batch_op:
        batch_op.drop_column('is_fixed_role')
        batch_op.drop_column('is_schedulable')

    op.drop_table('fixed_assignments')
    # ### end Alembic commands ###
