"""Add roster fields to Employee

Revision ID: 9c740d85ded2
Revises: f5e39eb652f4
Create Date: 2026-03-02 23:12:42.290685

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9c740d85ded2'
down_revision: Union[str, Sequence[str], None] = 'f5e39eb652f4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('employees', schema=None) as batch_op:
        batch_op.add_column(sa.Column('employee_id', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('shift_type', sa.Enum('DAY', 'AFTERNOON', 'NIGHT', name='shifttype'), nullable=True))
        batch_op.add_column(sa.Column('role_type', sa.Enum('SUPERVISOR', 'LOGISTICS', 'LINE_LEAD', 'SR_DOCK', 'GENERAL', name='roletype'), nullable=True))
        batch_op.add_column(sa.Column('employment_status', sa.Enum('ACTIVE', 'LOA', 'SUSPENDED', 'TERMINATED', name='employmentstatus'), nullable=True))
        batch_op.alter_column('department',
               existing_type=sa.VARCHAR(),
               nullable=True)
        batch_op.create_index(batch_op.f('ix_employees_employee_id'), ['employee_id'], unique=True)
        batch_op.drop_column('role')

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('employees', schema=None) as batch_op:
        batch_op.add_column(sa.Column('role', sa.VARCHAR(), nullable=False))
        batch_op.drop_index(batch_op.f('ix_employees_employee_id'))
        batch_op.alter_column('department',
               existing_type=sa.VARCHAR(),
               nullable=False)
        batch_op.drop_column('employment_status')
        batch_op.drop_column('role_type')
        batch_op.drop_column('shift_type')
        batch_op.drop_column('employee_id')

    # ### end Alembic commands ###
