"""add position_type to positions

Revision ID: f5e39eb652f4
Revises: 595b6831b310
Create Date: 2026-03-02 22:38:02.773320

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f5e39eb652f4'
down_revision: Union[str, Sequence[str], None] = '595b6831b310'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('positions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('position_type', sa.Enum('BREAK_RELIEF', 'MUFFIN_ANCHOR', 'BREAD_BUN_ANCHOR', 'PACKING_GENERAL', 'FLOATING', 'SHIPPING_FIXED', 'SHIPPING_ROTATIONAL', 'SHIPPING_DOCK', name='positiontype'), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('positions', schema=None) as batch_op:
        batch_op.drop_column('position_type')

    # ### end Alembic commands ###
