import subprocess
import sys
from pathlib import Path

def bootstrap_project(project_dir: Path):
    """
    Initializes a toolchain environment for the given project directory:
    - python -m venv venv
    - pip install -r requirements.txt
    - git init, add, commit
    """
    req_file = project_dir / "requirements.txt"
    
    # Python Environment
    if req_file.exists():
        subprocess.run([sys.executable, "-m", "venv", "venv"], cwd=project_dir, check=True)
        
        if sys.platform == "win32":
            pip_exe = project_dir / "venv" / "Scripts" / "pip.exe"
        else:
            pip_exe = project_dir / "venv" / "bin" / "pip"
            
        subprocess.run([str(pip_exe), "install", "-r", "requirements.txt"], cwd=project_dir, check=True)

    # Git Repository
    gitignore_content = "__pycache__/\nvenv/\n.venv/\n*.pyc\n.env\n"
    (project_dir / ".gitignore").write_text(gitignore_content)

    subprocess.run(["git", "init"], cwd=project_dir, check=True)
    subprocess.run(["git", "add", "."], cwd=project_dir, check=True)
    subprocess.run(
        ["git", "commit", "-m", "chore: initial artifact generated by intent compiler"], 
        cwd=project_dir, 
        check=False  # Allow failure if no user name configured, etc.
    )
